name: Auto Tag on Package Version Change

on:
  push:
    branches:
      - main

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.released }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Release
        id: release
        uses: justincy/github-action-npm-release@2.0.2

  build:
    runs-on: ubuntu-latest
    needs: check-release
    if: needs.check-release.outputs.released == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - run: pnpm i

      - name: Build
        run: pnpm build

  publish:
    runs-on: ubuntu-latest
    needs: 
      - build
      - check-release
    if: needs.check-release.outputs.released == 'true'
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - run: pnpm i

      - name: Publish
        run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
